### ISSUE TITLE
beach not visible in Cherry Creek SP (Colorado)

### ISSUE THREAD

**Issue by cldellow** [hikeratlas/basemap#2]
- [x] Brandywine Falls, Cuyahoga Valley NP ([OSM](https://www.openstreetmap.org/#map=18/41.27658/-81.53859), [local](http://localhost:8081/map#17.93/41.276735/-81.538885)) - "Bike and Hike Trail" MUP missing
- [x] Loft Mountain, Shenandoah NP ([OSM](https://www.openstreetmap.org/#map=17/38.24611/-78.66937), [local](http://localhost:8081/map#16.4/38.246764/-78.668314)) - parking and footpaths missing
- [ ] landcover in Cherry Creet SP (Colorado) ([OSM](https://www.openstreetmap.org/#map=13/39.6361/-104.8797), [local](http://localhost:8081/map#13.48/39.63649/-104.85674))
- [x] piers in Maligne Lake, Jasper NP ([OSM](https://www.openstreetmap.org/way/366199680#map=19/52.72865/-117.63985), [local](http://localhost:8081/map#15.6/52.727845/-117.639486))

**Comment by cldellow** [comment]
Split the MUP into #34, it's probably more involved

**Comment by cldellow** [comment]
re landcover in Cherry Creek: parks has a zindex of 10, land has a zindex of 2.

Beaches are styled in land, so the park is painting on top of the beach. This might require a more thoughtful solution - I feel like I want the current behaviour for low zooms, but for high zooms, maybe I want a park outline + allow the land to percolate through.
